# Generated by Django 4.2.8 on 2023-12-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
